version: "3"
services:
  mysql:
    image: mysql:8.0.17
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: db0
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
