version: "3"
services:
  mysql:
    image: mysql:8.0.17
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: db0
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  app1:
    build: .
    command: [
      "java",
      "--enable-preview",
      "-XX:+UseG1GC",
      "-Djava.rmi.server.hostname=127.0.0.1",
      "-Dcom.sun.management.jmxremote",
      "-Dcom.sun.management.jmxremote.rmi.port=8686",
      "-Dcom.sun.management.jmxremote.port=8686",
      "-Dcom.sun.management.jmxremote.local.only=false",
      "-Dcom.sun.management.jmxremote.ssl=false",
      "-Dcom.sun.management.jmxremote.authenticate=false",
      "-Xlog:gc*=debug:/root/gc_%t_%p.log:time,level,tags:filesize=1024m,filecount=5",
      "-XX:StartFlightRecording=name=on_startup,filename=/root/flight_recording.jfr,dumponexit=true,delay=2m,maxsize=512m",
      "-Xms1g",
      "-Xmx1g",
      "-jar",
      "/root/app.jar",
      "--spring.datasource.url=jdbc:mysql://mysql:3306/db0?characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true"
    ]
    ports:
      - 18080:8080
      - 18081:8081
      - 18686:8686
    depends_on:
      - mysql

  app2:
    build: .
    command: [
      "java",
      "--enable-preview",
      "-XX:+UnlockExperimentalVMOptions",
      "-XX:+UseZGC",
      "-Djava.rmi.server.hostname=127.0.0.1",
      "-Dcom.sun.management.jmxremote",
      "-Dcom.sun.management.jmxremote.rmi.port=8686",
      "-Dcom.sun.management.jmxremote.port=8686",
      "-Dcom.sun.management.jmxremote.local.only=false",
      "-Dcom.sun.management.jmxremote.ssl=false",
      "-Dcom.sun.management.jmxremote.authenticate=false",
      "-Xlog:gc*=debug:/root/gc_%t_%p.log:time,level,tags:filesize=1024m,filecount=5",
      "-XX:StartFlightRecording=name=on_startup,filename=/root/flight_recording.jfr,dumponexit=true,delay=2m,maxsize=512m",
      "-Xms1g",
      "-Xmx1g",
      "-jar",
      "/root/app.jar",
      "--spring.datasource.url=jdbc:mysql://mysql:3306/db0?characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true"
    ]
    ports:
      - 28080:8080
      - 28081:8081
      - 28686:8686
    depends_on:
      - mysql
