spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-usagenotes-connect-drivermanager.html
    url: jdbc:mysql://127.0.0.1:13306/db0?characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true
    username: test
    password: test

logging:
  level:
    info.matsumana.example: DEBUG

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.75, 0.9, 0.99, 0.999, 1.0
#    export:
#      datadog:
#        step: 15s
